
package com.ndr.free.jaxws.client.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SampleService4Port", targetNamespace = "http://free.ndr.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SampleService4Port {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sampleMetod", targetNamespace = "http://free.ndr.com", className = "com.ndr.free.jaxws.client.stubs.SampleMetod")
    @ResponseWrapper(localName = "sampleMetodResponse", targetNamespace = "http://free.ndr.com", className = "com.ndr.free.jaxws.client.stubs.SampleMetodResponse")
    public String sampleMetod(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
