
package com.ndr.free.jaxws.client.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SampleService3", targetNamespace = "http://free.ndr.com", wsdlLocation = "http://localhost:7001/FreeJaxWsProject1/SampleService3?WSDL")
public class SampleService3
    extends Service
{

    private final static URL SAMPLESERVICE3_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ndr.free.jaxws.client.stubs.SampleService3 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ndr.free.jaxws.client.stubs.SampleService3 .class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/FreeJaxWsProject1/SampleService3?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/FreeJaxWsProject1/SampleService3?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SAMPLESERVICE3_WSDL_LOCATION = url;
    }

    public SampleService3(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleService3() {
        super(SAMPLESERVICE3_WSDL_LOCATION, new QName("http://free.ndr.com", "SampleService3"));
    }

    /**
     * 
     * @return
     *     returns SampleService3Port
     */
    @WebEndpoint(name = "SampleService3PortPort")
    public SampleService3Port getSampleService3PortPort() {
        return super.getPort(new QName("http://free.ndr.com", "SampleService3PortPort"), SampleService3Port.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleService3Port
     */
    @WebEndpoint(name = "SampleService3PortPort")
    public SampleService3Port getSampleService3PortPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://free.ndr.com", "SampleService3PortPort"), SampleService3Port.class, features);
    }

}
