
package com.ndr.free.jaxws.client.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "SampleException2", targetNamespace = "http://free.ndr.com")
public class SampleException2_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SampleException2 faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SampleException2_Exception(String message, SampleException2 faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SampleException2_Exception(String message, SampleException2 faultInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ndr.free.jaxws.client.stubs.SampleException2
     */
    public SampleException2 getFaultInfo() {
        return faultInfo;
    }

}
